name: Update Leaderboard Data

on:
  schedule:
    # Runs every 15 minutes for faster badge updates
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      
      - name: Run scraper
        run: python scraper.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # Stage ONLY the two files you want to commit
          git add progress_data.csv google_cloud_badges_details.csv
          
          # Check if there are any changes to commit before proceeding
          if ! git diff --staged --quiet; then
            # Discard all other modified (but not staged) files
            git checkout -- .
            
            # Remove all other untracked files and directories
            git clean -fd
            
            # Now, commit and push the staged changes
            git commit -m "Auto-update leaderboard data"
            git pull --rebase
            git push
          else
            echo "No changes to commit."
          fi
